/*
 * Copyright (C) 2023-2025  Yomitan Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Custom error class for the extension which can contain extra data.
 * This works around an issue where assigning the `DOMException.data` field can fail on Firefox.
 * @see https://bugzilla.mozilla.org/show_bug.cgi?id=1776555
 */
export class ExtensionError extends Error {
    /**
     * @param {string} message
     */
    constructor(message) {
        super(message);
        /** @type {string} */
        this.name = 'ExtensionError';
        /** @type {unknown} */
        this._data = void 0;
    }

    /** @type {unknown} */
    get data() { return this._data; }
    set data(value) { this._data = value; }

    /**
     * Converts an `Error` object to a serializable JSON object.
     * @param {unknown} error An error object to convert.
     * @returns {import('core').SerializedError} A simple object which can be serialized by `JSON.stringify()`.
     */
    static serialize(error) {
        try {
            if (typeof error === 'object' && error !== null) {
                // Avoid destructuring/property reads that can throw when `error` is a host object
                // coming from native (QuickJS), which otherwise degrades into `[unsupported type]`.
                /** @type {import('core').SerializedError1} */
                const result = {name: '', message: '', stack: ''};

                try {
                    const name = /** @type {import('core').SerializableObject} */ (error).name;
                    if (typeof name === 'string') { result.name = name; }
                } catch (e) { /* NOP */ }

                try {
                    const message = /** @type {import('core').SerializableObject} */ (error).message;
                    if (typeof message === 'string') { result.message = message; }
                } catch (e) { /* NOP */ }

                try {
                    const stack = /** @type {import('core').SerializableObject} */ (error).stack;
                    if (typeof stack === 'string') { result.stack = stack; }
                } catch (e) { /* NOP */ }

                if (error instanceof ExtensionError) {
                    try {
                        result.data = error.data;
                    } catch (e) { /* NOP */ }
                }

                return result;
            }
        } catch (e) {
            // NOP
        }
        let value;
        try {
            value = String(error);
        } catch (e) {
            value = '[unsupported type]';
        }
        return /** @type {import('core').SerializedError2} */ ({value, hasValue: true});
    }

    /**
     * Converts a serialized error into a standard `Error` object.
     * @param {import('core').SerializedError} serializedError A simple object which was initially generated by the `serialize` function.
     * @returns {ExtensionError} A new `Error` instance.
     */
    static deserialize(serializedError) {
        if (serializedError.hasValue) {
            // Use `var` (not `const`/`let`) to avoid temporal-dead-zone related
            // ReferenceErrors observed in some QuickJS builds.
            // eslint-disable-next-line no-var
            var errorValue = /** @type {import('core').SerializedError2} */ (serializedError).value;
            return new ExtensionError(`Error of type ${typeof errorValue}: ${String(errorValue)}`);
        }
        const {message, name, stack, data} = serializedError;
        const error = new ExtensionError(message);
        error.name = name;
        error.stack = stack;
        if (typeof data !== 'undefined') {
            error.data = data;
        }
        return error;
    }
}
